feat(brand logo): add support for logo on title
Pelican-Elegant/elegant pull request #645
Opened 2020-11-01 19:51 UTC by f-fouad

## Prerequisites

- [X] My Pull Request is filled against the `next` branch
- [X] All commits in my Pull Request conform to [Elegant Git commit Guidelines](https://elegant.oncrashreboot.com/git-commit-guidelines)

## Recommended Steps

- [X] My patch adds a new feature, therefore I have also added a help article about it
- [X] My patch changes Elegant behavior, therefore I have updated the help article to reflect this change
- [ ] My commits are [signed](https://help.github.com/en/articles/signing-commits)

## Description

Added an optional variable `DISPLAY_BRAND_LOGO`, if defined, a logo image will be displayed Left of the site title in the navigation bar. The variable's value should be the url to the brand logo file.

An example in pelicanconf.py would be :  

```
DISPLAY_BRAND_LOGO = SITEURL + "/images/logo.png"
```

Or

```
DISPLAY_BRAND_LOGO = "/images/logo.png"
```

2020-11-03 16:45 UTC, talha131 commented
Thank you @f-fouad I will merge it soon. My python setup is broken on my Mac machine (most probably because I am running beta macOS). As soon as it gets fixed, I will merge and release a new version of Elegant.

2021-09-10 07:22 UTC, iranzo requested changes

2021-09-10 07:22 UTC, iranzo commented on templates/base.html
> +                                <img src="{{ DISPLAY_LOGO_ON_TITLE }}" alt="brand-logo">
If Using DISPLAY_BRAND_LOGO the IMG SRC should be the same variable, if not, it sets an undefined variable

2021-09-10 07:24 UTC, iranzo commented
Additionally I would consider creating an article (full article) with the feature to be added to the documentation. 

Let me know if you can work on this @f-fouad so that we can merge this. Great addition!

2021-09-10 14:43 UTC, iranzo commented
Apart of the pelican logo, the variable used for enabling/disabling and the one used for 'showing' the actual icon are different ;-)

2021-09-10 14:49 UTC, iranzo commented
@f-fouad are you going to write a small doc article regarding the feature?

2021-09-10 15:03 UTC, f-fouad commented
Thank you for taking the time and effort to review it.

I am looking for an example of doc article right now (some guidance is welcome). Probably, it will take me some time because I am not accustomed to git/github (first pull request).

2021-09-10 15:05 UTC, iranzo commented
It's a matter of adding a file like 'https://github.com/Pelican-Elegant/elegant/blob/master/documentation/content/Components/site-subtitle.md' but with 'site-logo' for example :) (and fill the contents there)

2021-09-10 15:28 UTC, iranzo commented
Thank you!

2021-09-10 15:29 UTC, merged